server:
  port: 1007
  maxHttpHeaderSize: 1024000  #单位byte,最大请求头数据大小，默认是8k
feign: 
  hystrix: 
    enabled: false
  httpclient:
    enabled: true
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka/
  instance: 
    prefer-ip-address: true

logging:
  config: 'classpath:logback.xml'
  #file-name: pc
  level-service: INFO  
    
# 配置freemarker
spring:
  mvc:
    static-path-pattern: /resources/**
  resources: 
    static-locations: classpath:/resources/ 
    
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html;charset=UTF-8
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    request-context-attribute: request
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
   
yxkj: 
  urlResources: http://127.0.0.1:1007
  staticResources: http://127.0.0.1:1007/resources/front
  imageResources: http://127.0.0.1:8888/ejsimage
  cookieDomain: 127.0.0.1
  cookieName: qiqu_b2b2c_pc
  frontUrl: http://127.0.0.1:1007
  h5Url: http://127.0.0.1
  searchSolrUrl: http://127.0.0.1:8888/solr
  searchSolrServer: ejavashopcore
  pomLogFile: pc
  pomLogLevel: debug
