server:
  port: 1006
  maxHttpHeaderSize: 1024000  #单位byte,最大请求头数据大小，默认是8k
feign: 
  hystrix: 
    enabled: false
  httpclient:
    enabled: true
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 6000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka/

logging:
  config: 'classpath:logback.xml'
  #file-name: mobile
  level-service: INFO  

# 配置freemarker
spring:
  mvc:
    static-path-pattern: /resources/**
  resources: 
    static-locations: classpath:/resources/ 
   
yxkj: 
  urlResources: http://127.0.0.1
  staticResources: http://127.0.0.1:1006/resources/h5
  imageResources: http://127.0.0.1:8888/ejsimage
  cookieDomain: 127.0.0.1
  cookieName: qiqu_b2b2c_mobile
  frontUrl: http://127.0.0.1
  h5Url: http://127.0.0.1
  searchSolrUrl: http://127.0.0.1:8888/solr
  searchSolrServer: ejavashopcore
  pomLogFile: mobile
  pomLogLevel: debug
