server:
  port: 7001

spring:
  security:
    user:
      name: qiqu
      password: qiqu2019
  application:
    name: qiqu-eureka
  cloud:
    config:
      enabled: false

# docker-compose部署时候 hostname 换成qiqu-eureka
# 类似的 redis 使用qiqu-redis ,gateway 换成 qiqu-gateway
eureka:
  instance:
    hostname: qiqu-eureka
    prefer-ip-address: true
  client:
    register-with-eureka: false        #false表示不向注册中心注册自己。
    fetch-registry: false              #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://192.168.0.4:7001/eureka/   #目前为单机注册中心  后期搭建集群 使用负载均衡IP
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: false
    renewal-percent-threshold: 0.9

management:
  endpoints:
    web:
      exposure:
        include: '*'